import "./buffer-stream.test.js";
import "./is-duplex-stream.test.js";
import "./is-readable-stream.test.js";
import "./is-writable-stream.test.js";
import "./iterator-stream.test.js";
import "./to-buffer.test.js";
import "./to-json.test.js";
import "./to-readable.test.js";
import "./to-text.test.js";
