import "./get-dependencies.test.js";
import "./get-injections.test.js";
import "./get-scope.test.js";
import "./get-tags.test.js";
import "./is-injectable.test.js";
import "./set-injectable.test.js";
import "./set-injections.test.js";
import "./set-scope.test.js";
import "./set-tags.test.js";
